FROM golang:1.21-alpine AS build
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o /tmp/{{snake .ServiceName}} ./services/{{.ServiceName}}/server

FROM alpine:3.22
EXPOSE 8000
ENV PORT=8000
RUN apk add --no-cache tini
USER nobody
WORKDIR /app
COPY --from=build /tmp/{{snake .ServiceName}} /app/{{snake .ServiceName}}
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["./{{snake .ServiceName}}"]
